name: 'Request Review Based on Files'
description: 'Request review based on files changed'
inputs:
  token:
    required: true
  config:
    required: false
    default: '.github/request-review-based-on-files.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
